-- Comprehensive FAQ seed from FAQ.md
-- Generated by scripts/seed-faq-from-markdown.ts
-- Run: psql $DATABASE_URL -f backend/drizzle/seed-faq-full.sql

-- First, clear existing manual/approved entries (keep user_confirmed and gemini/groq entries)
DELETE FROM faq_entries WHERE source IN ('manual', 'approved');

INSERT INTO faq_entries (question_fa, answer_fa, question_en, answer_en, category, tags, source, is_published, confidence)
VALUES
  (
    'این سیستم چیست و برای چه کسانی طراحی شده است؟',
    'این یک سیستم CRM (مدیریت ارتباط با مشتری) پزشکی است که برای کلینیک‌های زنان و زایمان و عمومی طراحی شده است. ابزارهایی برای مدیریت بیماران، نوبت‌دهی، نسخه‌ها، نتایج آزمایش، صورتحساب، انبار، کارکنان و ارتباط با بیماران فراهم می‌کند. توسط پزشکان، مدیران کلینیک، تکنسین‌های آزمایشگاه، کارکنان داروخانه و کارکنان عمومی کلینیک استفاده می‌شود.',
    'What is this system and who is it for?',
    'This is a medical clinic CRM (Customer Relationship Management) system designed for OB/GYN and general medical clinics. It provides tools for managing patients, appointments, prescriptions, lab results, billing, inventory, staff, and patient communication. It is used by doctors, clinic administrators, lab technicians, pharmacy staff, and general clinic staff.',
    'general',
    ARRAY['general', 'patients', 'scheduling', 'prescriptions', 'lab', 'billing', 'inventory']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چه نقش‌هایی در سیستم وجود دارد؟',
    'شش نقش کاربری وجود دارد:
- **پزشک مدیر** — دسترسی کامل به تمام بخش‌ها شامل تنظیمات، مدیریت کاربران و حسابداری.
- **پزشک** — دسترسی به ابزارهای بالینی، بیماران، نوبت‌دهی، نسخه‌ها، نتایج آزمایش و پیام‌رسانی.
- **تکنسین آزمایشگاه** — دسترسی به نتایج آزمایش و پیام‌رسانی.
- **کارمند داروخانه** — دسترسی به نسخه‌ها، انبار و پیام‌رسانی.
- **کارمند کلینیک** — دسترسی به حضور و غیاب، برنامه/وظایف و پیام‌رسانی.
- **بیمار** — دسترسی محدود به نوبت‌دهی، پرونده شخصی و پیام‌رسانی.',
    'What roles exist in the system?',
    'There are six user roles:
- **Admin Doctor** — Full access to all features including settings, user management, and accounting.
- **Doctor** — Access to clinical tools, patients, scheduling, prescriptions, lab results, and messaging.
- **Lab Technician** — Access to lab results and messaging.
- **Pharmacy Staff** — Access to prescriptions, inventory, and messaging.
- **Clinic Staff** — Access to attendance, schedule/tasks, and messaging.
- **Patient** — Limited access to booking, their own records, and messaging.',
    'general',
    ARRAY['general', 'patients', 'scheduling', 'prescriptions', 'lab', 'inventory', 'messaging', 'attendance']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگوره وارد سیستم شوم؟',
    'به صفحه ورود بروید و شماره تلفن و رمز عبور خود را وارد کید. اگر وضعیت حساب شما «در انتظار تأیید» است، باید منتظر تأیید مدیر سیستم باشید.',
    'How do I log in?',
    'Navigate to the login page and enter your phone number and password. If your account status is "pending," you must wait for an administrator to approve your registration before you can log in.',
    'general',
    ARRAY['general', 'login', 'attendance']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'رمز عبورم را فراموش کرده‌ام. چه کار کنم؟',
    'روی «فراموشی رمز عبور» در صفحه ورود کلیک کنید. شماره تلفن ثبت‌شده خود را وارد کنید. یک رمز یکبار مصرف (OTP) از طریق پیامک دریافت خواهید کرد. OTP و رمز عبور جدید را وارد کنید.',
    'I forgot my password. How do I reset it?',
    'Click "Forgot Password" on the login page. Enter your registered phone number. You will receive a one-time password (OTP) via SMS. Enter the OTP and your new password to complete the reset.',
    'general',
    ARRAY['general', 'login', 'patients', 'messaging', 'attendance']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'در اولین ورود ملزم به تغییر رمز عبور هستم. چگونه این کار را انجام دهم؟',
    'پس از اولین ورود، پرامپتی نمایش داده می‌شود که از شما می‌خواهد رمز عبور جدیدی تنظیم کنید. همچنین می‌توانید در هر زمان از بخش **پروفایل من** > **تغییر رمز عبور** استفاده کنید.

---',
    'I''m required to change my password on first login. How do I do that?',
    'After your first login, a prompt will appear asking you to set a new password. You can also change your password at any time from **My Profile** > **Change Password**.',
    'general',
    ARRAY['general', 'login', 'attendance', 'profile']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'Can I log in from multiple devices?',
    'Yes, you can log in from multiple devices. However, each new login generates a fresh JWT token. For security, if you suspect unauthorized access, change your password immediately.',
    'Can I log in from multiple devices?',
    'Yes, you can log in from multiple devices. However, each new login generates a fresh JWT token. For security, if you suspect unauthorized access, change your password immediately.',
    'general',
    ARRAY['general', 'login']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'What happens if I enter the wrong password too many times?',
    'The system applies rate limiting to login attempts. After several failed attempts, you will be temporarily blocked from trying again. Wait a few minutes and try again, or use the "Forgot Password" flow.

---',
    'What happens if I enter the wrong password too many times?',
    'The system applies rate limiting to login attempts. After several failed attempts, you will be temporarily blocked from trying again. Wait a few minutes and try again, or use the "Forgot Password" flow.

---',
    'general',
    ARRAY['general', 'login']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'داشبورد مدیر چه اطلاعاتی نشان می‌دهد؟',
    'داشبورد مدیر شامل:
- کارت‌های آماری (تعداد کل بیماران، نوبت‌های امروز، وظایف در انتظار و غیره).
- نمودارها و گراف‌های روند بیماران و نوبت‌ها.
- فید فعالیت‌های اخیر.
- دسترسی سریع به بخش‌های کلیدی.',
    'What does the admin dashboard show?',
    'The admin dashboard displays:
- Total patients, today''s appointments, pending tasks, and other summary stat cards.
- Charts and graphs showing patient trends and appointment data.
- Recent activity feed.
- Quick access to key sections.',
    'general',
    ARRAY['general', 'patients', 'scheduling']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'داشبورد بیمار چه اطلاعاتی نشان می‌دهد؟',
    'اگر کاربر وارد شده یک بیمار نیز باشد، داشبورد او شامل:
- تعداد پیام‌های خوانده‌نشده.
- نوبت‌های آینده و گذشته.
- دسترسی سریع به نسخه‌ها و پرونده‌ها.

---',
    'What does the patient dashboard show?',
    'If a logged-in user is also a patient, their dashboard shows:
- Unread message count.
- Upcoming and past appointments.
- Quick links to prescriptions and records.',
    'general',
    ARRAY['general', 'patients', 'scheduling', 'prescriptions', 'messaging']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'The dashboard is loading slowly. What can I do?',
    'The dashboard features a cinematic loading screen with animations. If it takes too long, check your internet connection. The system uses server-side data aggregation; slow performance may indicate a backend issue — contact your system administrator.

---',
    'The dashboard is loading slowly. What can I do?',
    'The dashboard features a cinematic loading screen with animations. If it takes too long, check your internet connection. The system uses server-side data aggregation; slow performance may indicate a backend issue — contact your system administrator.

---',
    'general',
    ARRAY['general']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه یک بیمار جدید ثبت کنم؟',
    'به بخش **بیماران** بروید و روی **+ ثبت بیمار جدید** کلیک کنید. اطلاعات بیمار را در تب‌های زیر وارد کنید:
1. **اطلاعات پایه** — نام، نام خانوادگی، کد ملی، تلفن، تاریخ تولد، آدرس، بیمه، وضعیت تأهل.
2. **سابقه پزشکی** — بیماری‌های فعلی، داروها، آلرژی‌ها، سابقه خانوادگی.
3. **سابقه بارداری** — خلاصه بارداری/زایمان، تاریخچه قاعدگی، جراحی‌های زنانه، تاریخچه ضد بارداری.
4. **واکسیناسیون** — سابقه واکسن‌ها (نام، دوز، تاریخ، شماره لوت، سازنده).
5. **پیوست‌ها** — آپلود فایل‌ها مانند تصاویر سونوگرافی، گزارش آزمایش یا نسخه.

روی **ذخیره** کلیک کنید.',
    'How do I add a new patient?',
    'Go to **Patients** and click the **+ Add Patient** button. Fill in the patient''s information across the following tabs:
1. **Basic Info** — First name, last name, national ID, phone, birth date, address, insurance details, marital status.
2. **Medical History** — Current diseases, medications, allergies, family history.
3. **Pregnancy History** — Gravida/para summary, menstrual history, gynecological surgeries, contraceptive history.
4. **Vaccination** — Vaccine records (name, dose, date, lot number, manufacturer, next dose).
5. **Attachments** — Upload files such as ultrasound images, lab reports, or prescriptions.

Click **Save** to create the patient record.',
    'patients',
    ARRAY['patients', 'prescriptions', 'lab']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه یک بیمار را جستجو کنم؟',
    'در صفحه **بیماران**، از نوار جستجو استفاده کنید. جستجو بر اساس نام، کد ملی یا شماره تلفن امکان‌پذیر است. همچنین می‌توانید بر اساس وضعیت تأهل فیلتر کنید.',
    'How do I search for a patient?',
    'On the **Patients** page, use the search bar to search by name, national ID, or phone number. You can also filter by marital status. The search is debounced (400ms) for performance.',
    'patients',
    ARRAY['patients']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه اطلاعات یک بیمار را ویرایش کنم؟',
    'از لیست بیماران، روی نام یا ردیف بیمار کلیک کنید تا صفحه جزئیات باز شود. از آنجا می‌توانید اطلاعات را ویرایش کنید. همچنین با کلیک روی آیکون ویرایش در جدول، فرم ویرایش باز می‌شود.',
    'How do I edit an existing patient''s information?',
    'From the patient list, click on the patient''s name or row to open their detail page. From there, you can edit their information. Alternatively, click the edit icon in the table to open the edit form dialog with all the same tabs available during creation.',
    'patients',
    ARRAY['patients', 'lab']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'آیا می‌توانم پرونده بیمار را حذف کنم؟',
    'بله. پرونده‌های بیماران به صورت حذف نرم (soft-delete) حذف می‌شوند و از نمای عادی پنهان می‌شوند. این عملیات فقط توسط پزشک مدیر/پزشک قابل انجام است.',
    'Can I delete a patient record?',
    'Yes, patient records are soft-deleted (not permanently removed). The record is marked as deleted and hidden from normal views. This is an admin/doctor-level action.',
    'patients',
    ARRAY['patients']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه پیوست به پرونده بیمار اضافه کنم؟',
    'فرم بیمار (ثبت یا ویرایش) را باز کنید و به تب **پیوست‌ها** بروید. می‌توانید فایل‌ها را drag-and-drop یا انتخاب کنید. حداکثر حجم فایل ۱۰ مگابایت و حداکثر ۵۰ فایل در هر بار آپلود است.

---',
    'How do I upload attachments to a patient''s file?',
    'Open the patient form (add or edit) and go to the **Attachments** tab. You can drag-and-drop or browse for files. Supported attachment types include ultrasound images, lab reports, prescriptions, and general patient files. The maximum file size is 10 MB per file, and you can upload up to 50 files at once.',
    'patients',
    ARRAY['patients', 'prescriptions', 'lab']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I view a patient''s full printable record?',
    'From the patient detail page, there is an option to generate a **Full Record** (printable view) that compiles all patient information — demographics, medical history, visits, prescriptions, lab results, and attachments — into a single printable format.',
    'How do I view a patient''s full printable record?',
    'From the patient detail page, there is an option to generate a **Full Record** (printable view) that compiles all patient information — demographics, medical history, visits, prescriptions, lab results, and attachments — into a single printable format.',
    'patients',
    ARRAY['patients', 'prescriptions', 'lab']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I send an SMS to a patient?',
    'From the patient list or detail page, use the **Send SMS** action. The system will send the message via the configured SMS provider. SMS usage is tracked and visible in the admin settings.',
    'How do I send an SMS to a patient?',
    'From the patient list or detail page, use the **Send SMS** action. The system will send the message via the configured SMS provider. SMS usage is tracked and visible in the admin settings.',
    'patients',
    ARRAY['patients', 'messaging', 'settings']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'What is the difference between national ID and insurance code?',
    'The **National ID** (کد ملی) is a unique 10-digit Iranian national identification number assigned to every citizen. It serves as the primary unique identifier for patients. The **Insurance Code** is a separate number tied to the patient''s health insurance plan and is used for insurance claim processing.',
    'What is the difference between national ID and insurance code?',
    'The **National ID** (کد ملی) is a unique 10-digit Iranian national identification number assigned to every citizen. It serves as the primary unique identifier for patients. The **Insurance Code** is a separate number tied to the patient''s health insurance plan and is used for insurance claim processing.',
    'patients',
    ARRAY['patients']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'What insurance types are supported?',
    'The system supports the following insurance types:
- Social Security (Tamin Ejtemaei)
- Health Insurance (Bimeh Salamat)
- Armed Forces Insurance (Niroohaye Mosallah)
- Relief Committee (Komiteh Emad)
- Iran Insurance (Bimeh Iran)
- Supplementary Insurance (Takmili)
- Other

---',
    'What insurance types are supported?',
    'The system supports the following insurance types:
- Social Security (Tamin Ejtemaei)
- Health Insurance (Bimeh Salamat)
- Armed Forces Insurance (Niroohaye Mosallah)
- Relief Committee (Komiteh Emad)
- Iran Insurance (Bimeh Iran)
- Supplementary Insurance (Takmili)
- Other

---',
    'patients',
    ARRAY['patients']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه تقویم بالینی را ببینم؟',
    'از بخش **تقویم** در نوار کناری استفاده کنید. تقویم از FullCalendar استفاده می‌کند و تمام ویزیت‌ها و نوبت‌ها را در نمای هفتگی/ماهانه/روزانه نشان می‌دهد.',
    'How do I view the clinical calendar?',
    'Navigate to **Calendar** from the Clinical section in the sidebar. The calendar uses FullCalendar and displays all visits and appointments in a weekly/monthly/daily view. You can click on a time slot to create a new visit, or click on an existing event to view or edit it.',
    'clinical',
    ARRAY['clinical', 'patients', 'scheduling']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه یک ویزیت بالینی ثبت کنم؟',
    'از بخش تقویم یا نوبت‌ها، روی ایجاد ویزیت کلیک کنید. بیمار را انتخاب کنید (جستجو بر اساس نام یا کد ملی)، نوع ویزیت را انتخاب کنید، تاریخ و ساعت را تنظیم کنید، دلیل ویزیت و یادداشت‌ها را اضافه کنید و ذخیره کنید.',
    'How do I record a clinical visit?',
    'From the Calendar or Appointments page, you can create a visit by:
1. Selecting the patient (search by name or national ID).
2. Choosing the visit type.
3. Setting the date and time.
4. Adding visit reason, notes, and duration.
5. Saving the visit record.',
    'clinical',
    ARRAY['clinical', 'patients', 'scheduling']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'انواع ویزیت چیست و چگونه آن‌ها را مدیریت کنم؟',
    'انواع ویزیت دسته‌بندی‌های ویزیت‌های بالینی کلینیک شما هستند (مثلاً مشاوره، پیگیری، سونوگرافی). هر نوع شامل نام، توضیحات، مدت زمان، قیمت و رنگ است. از بخش **انواع ویزیت** می‌توانید آن‌ها را ایجاد، ویرایش یا غیرفعال کنید.

---',
    'What are Visit Types and how do I manage them?',
    'Visit Types define the categories of clinical visits your clinic offers (e.g., Consultation, Follow-up, Ultrasound). Each visit type has a name, description, duration, price, and color. Go to **Visit Types** to create, edit, or deactivate visit types. Each doctor can have their own set of visit types.',
    'clinical',
    ARRAY['clinical', 'patients']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I record vital signs for a patient?',
    'Vital signs are recorded as part of the clinical workflow. During a visit, you can log:
- Blood pressure (systolic/diastolic)
- Heart rate
- Respiratory rate
- Temperature
- Oxygen saturation
- Weight, height, BMI
- Pain score (0–10)

Vital signs are linked to the specific visit and patient record.

---',
    'How do I record vital signs for a patient?',
    'Vital signs are recorded as part of the clinical workflow. During a visit, you can log:
- Blood pressure (systolic/diastolic)
- Heart rate
- Respiratory rate
- Temperature
- Oxygen saturation
- Weight, height, BMI
- Pain score (0–10)

Vital signs are linked to the specific visit and patient record.

---',
    'clinical',
    ARRAY['clinical', 'patients']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه زمان‌های در دسترس هفتگی خود را تنظیم کنم؟',
    'به بخش **برنامه‌ریزی** در نوار کناری بروید. یک جدول هفتگی (شنبه تا جمعه) مشاهده خواهید کرد. روی یک زمان کلیک کنید تا ساعت‌های در دسترس خود را اضافه کنید. فقط زمان‌های فعال قابل رزرو توسط بیماران هستند.',
    'How do I set up my weekly availability?',
    'Go to **Scheduling** in the sidebar. You''ll see a weekly timetable grid (Saturday through Friday). Click on a time slot to add your available hours. You can define start and end times for each day. Only active time slots are bookable by patients.',
    'scheduling',
    ARRAY['scheduling', 'patients', 'lab']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'مدیر چگونه برنامه پزشک دیگری را مدیریت کند؟',
    'به **مدیریت > برنامه مدیریتی** بروید. پزشک مورد نظر را از منوی کشویی انتخاب کنید. جدول هفتگی او نمایش داده می‌شود. روی زمان کلیک کنید تا بازه‌های زمانی را اضافه، ویرایش یا حذف کنید.',
    'How do I manage another doctor''s schedule as an admin?',
    'Go to **Admin > Admin Schedule**. Select the doctor from the dropdown. You''ll see their weekly timetable. Click to add, edit, or delete availability slots. Admins have full override access to any doctor''s schedule.',
    'scheduling',
    ARRAY['scheduling', 'lab']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه نوبت‌های امروز را ببینم؟',
    'به بخش **نوبت‌ها** بروید. صفحه به طور پیش‌فرض لیست نوبت‌های امروز را نشان می‌دهد. از **ناوبر تاریخ** (فلش‌های قبلی/بعدی) برای مشاهده روزهای دیگر استفاده کنید.',
    'How do I view today''s appointments?',
    'Go to **Appointments** in the sidebar. The page shows today''s appointment list by default. Use the **Date Navigator** (prev/next arrows) to browse other days. Each appointment card shows the time, patient name, visit type, status, and available actions.',
    'scheduling',
    ARRAY['scheduling', 'patients', 'lab']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه یک نوبت را تأیید یا رد کنم؟',
    'در لیست نوبت‌ها، دکمه‌های عملیاتی برای هر نوبت وجود دارد:
- **تأیید** — نوبت را تأیید کنید.
- **رد** — نوبت را لغو کنید (با دلیل اختیاری).
- **ارسال یادآوری پیامکی** — پیامک یادآوری به بیمار ارسال کنید.',
    'How do I confirm or reject an appointment?',
    'In the Appointments list, each appointment has action buttons. You can:
- **Confirm** — Mark the appointment as confirmed.
- **Reject** — Cancel the appointment (with optional reason).
- **Send SMS Reminder** — Send a reminder message to the patient.',
    'scheduling',
    ARRAY['scheduling', 'patients', 'messaging']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'آیا بیماران می‌توانند مستقیماً نوبت رزرو کنند؟',
    'بله. بیماران از طریق صفحه **رزرو عمومی** (`/booking`) بدون نیاز به ورود، **اپلیکیشن تلگرام** یا **حضوری** می‌توانند نوبت رزرو کنند.',
    'Can patients book appointments directly?',
    'Yes. Patients can book through:
1. The **public booking page** (`/booking`) — no login required.
2. The **Telegram Mini App** — for Telegram-linked patients.
3. Walk-in appointments created by staff.

Public booking shows available doctors, services, and time slots without requiring authentication.',
    'scheduling',
    ARRAY['scheduling', 'login', 'patients', 'lab', 'attendance', 'telegram']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'فرآیند رزرو عمومی چگونه کار می‌کند؟',
    'فرآیند رزرو در مراحل:
1. انتخاب نوع خدمت (نوع ویزیت).
2. انتخاب پزشک.
3. انتخاب تاریخ.
4. انتخاب ساعت در دسترس.
5. وارد کردن اطلاعات بیمار (نام، تلفن، کد ملی).
6. تأیید رزرو.

نوبت با وضعیت «در انتظار» ایجاد می‌شود و کارکنان می‌توانند آن را تأیید یا رد کنند.

---',
    'How does the public booking flow work?',
    'The public booking flow at `/booking` works in steps:
1. Select a service type (visit type).
2. Choose a doctor.
3. Pick a date.
4. Select an available time slot.
5. Enter patient information (name, phone, national ID).
6. Confirm the booking.

The appointment is created with a "pending" status and the staff can confirm or reject it.',
    'scheduling',
    ARRAY['scheduling', 'patients', 'lab']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'Can I define visit type prices for booking?',
    'Yes. Each visit type has a **price** field. This price is displayed to patients during the booking flow and is used for billing records when the appointment is completed.

---',
    'Can I define visit type prices for booking?',
    'Yes. Each visit type has a **price** field. This price is displayed to patients during the booking flow and is used for billing records when the appointment is completed.

---',
    'scheduling',
    ARRAY['scheduling', 'patients', 'billing']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چه ابزارهای ارزیابی بالینی موجود است؟',
    '- **معیارهای Rotterdam برای سندرم پلی‌کیستیک تخمدان (PCOS)** — ارزیابی بر اساس معیارهای Rotterdam.
- **نمره یائسگی** — ارزیابی علائم یائسگی.
- **نمره Bishop** — ارزیابی آمادگی سرویکس برای القای زایمان.
- **ارزیابی خطر سرطان پستان** — ارزیابی عوامل خطر سرطان پستان.',
    'What clinical assessment tools are available?',
    'The Clinical Tools page provides the following calculators:
- **PCOS Rotterdam Criteria** — Assesses polycystic ovary syndrome based on Rotterdam criteria (menstrual irregularity, hyperandrogenism, ultrasound findings).
- **Menopause Score** — Evaluates menopausal symptoms using a scoring system.
- **Bishop Score** — Assesses cervical readiness for labor induction.
- **Breast Cancer Risk Assessment** — Evaluates breast cancer risk factors.

Each tool provides a score, interpretation, and stores the result in the patient''s clinical assessment history.',
    'clinical',
    ARRAY['clinical', 'patients', 'lab']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'بخش غربالگری برای چیست؟',
    'بخش **غربالگری** برنامه‌های غربالگری بهداشتی پیشگیرانه را مدیریت می‌کند. می‌توانید برای بیماران غربالگری برنامه‌ریزی کنید (مثلاً پاپ اسمیر، ماموگرافی)، تاریخ سررسید و سطح خطر را تعیین کنید و نتایج را ثبت کنید.

---',
    'How do I run a PCOS assessment?',
    'Go to **Clinical Tools**, select **PCOS Rotterdam**. Choose the patient, then fill in the criteria:
- Irregular menstrual cycles
- Clinical or biochemical hyperandrogenism
- Polycystic ovaries on ultrasound

The system calculates the score and provides a clinical interpretation. Results are saved to the patient''s record.',
    'clinical',
    ARRAY['clinical', 'patients', 'scheduling', 'lab']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'What is the Screening section for?',
    'The **Screening** section manages preventive health screening programs. You can:
- Schedule screenings for patients (e.g., Pap smear, mammogram, bone density).
- Set due dates and risk levels.
- Record screening results and outcomes.
- Track overdue and upcoming screenings.',
    'What is the Screening section for?',
    'The **Screening** section manages preventive health screening programs. You can:
- Schedule screenings for patients (e.g., Pap smear, mammogram, bone density).
- Set due dates and risk levels.
- Record screening results and outcomes.
- Track overdue and upcoming screenings.',
    'clinical',
    ARRAY['clinical', 'patients', 'scheduling', 'lab']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I schedule a screening for a patient?',
    'Go to **Screening** > **Add New Schedule**. Select the patient, screening type, due date, risk level, and assign a provider. Save the schedule. The system will track the screening status and alert you when it''s due or overdue.',
    'How do I schedule a screening for a patient?',
    'Go to **Screening** > **Add New Schedule**. Select the patient, screening type, due date, risk level, and assign a provider. Save the schedule. The system will track the screening status and alert you when it''s due or overdue.',
    'clinical',
    ARRAY['clinical', 'patients', 'scheduling']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I view overdue screenings?',
    'Go to **Screening** and use the **Overdue** filter or tab. The system automatically calculates which screenings are past their due date based on the scheduled due date.

---',
    'How do I view overdue screenings?',
    'Go to **Screening** and use the **Overdue** filter or tab. The system automatically calculates which screenings are past their due date based on the scheduled due date.

---',
    'clinical',
    ARRAY['clinical', 'scheduling']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه نتایج آزمایش بیمار را ببینم؟',
    'به بخش **نتایج آزمایش** بروید و بیمار را بر اساس نام یا کد ملی جستجو کنید. نتایج بر اساس دسته‌بندی (مثلاً بیوشیمی، هماتولوژی، هورمون‌ها) نمایش داده می‌شوند.',
    'How do I view a patient''s lab results?',
    'Go to **Lab Results**, search for the patient by name or national ID. The page displays all lab results organized by category (e.g., biochemistry, hematology, hormones). You can filter by category and report type.',
    'lab_results',
    ARRAY['lab_results', 'patients', 'lab']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه نتیجه آزمایش جدید اضافه کنم؟',
    'از صفحه نتایج آزمایش، روی دکمه اضافه کلیک کنید. بیمار را انتخاب کنید، سپس نام تست، کد، دسته‌بندی، مقدار نتیجه، واحد، محدوده مرجع و وضعیت غیرطبیعی بودن را وارد کنید.',
    'How do I add a new lab result?',
    'From the Lab Results page, click the add button. Select the patient, then fill in:
- Test name and code
- Category (e.g., biochemistry, hematology)
- Result value and unit
- Reference range (low/high)
- Whether the result is abnormal
- Report type and date

Results can also be linked to a specific lab order and visit.',
    'lab_results',
    ARRAY['lab_results', 'patients', 'lab']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه روند نتایج آزمایش را پیگیری کنم؟',
    'برای هر تست آزمایش، می‌توانید **نمودار روند** را مشاهده کنید که مقادیر تاریخی را در طول زمان نمایش می‌دهد.',
    'How do I track lab result trends?',
    'For any lab test, you can view a **trend chart** that plots historical values over time. This helps track changes in parameters like blood glucose, cholesterol, or hormone levels across multiple visits.',
    'lab_results',
    ARRAY['lab_results', 'lab']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه نسخه ایجاد کنم؟',
    'به بخش **نسخه‌ها** بروید، بیمار را جستجو کنید و **افزودن نسخه** را بزنید. نام دارو، دوز و دفعات مصرف، مسیر مصرف، مدت زمان، تعداد و دستورات را وارد کنید.

---',
    'How do I create a prescription?',
    'Go to **Prescriptions**, search for the patient, and click **Add Prescription**. Fill in:
- Medication name
- Dosage and frequency
- Route (oral, topical, etc.)
- Duration and quantity
- Refills allowed
- Instructions and notes
- Start and end dates

You can also discontinue an active prescription with a reason.',
    'lab_results',
    ARRAY['lab_results', 'patients', 'prescriptions']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I view a patient''s active prescriptions?',
    'From the Prescriptions page, search for the patient. The system shows all prescriptions with a filter for **Active** prescriptions only. Active prescriptions are those with `isCurrent = true` and no discontinuation date.

---',
    'How do I view a patient''s active prescriptions?',
    'From the Prescriptions page, search for the patient. The system shows all prescriptions with a filter for **Active** prescriptions only. Active prescriptions are those with `isCurrent = true` and no discontinuation date.

---',
    'lab_results',
    ARRAY['lab_results', 'patients', 'prescriptions']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه رکورد صورتحساب ایجاد کنم؟',
    'به بخش **صورتحساب** بروید و **افزودن رکورد** را کلیک کنید. بیمار و کد عملیات را انتخاب کنید، مبلغ، مبلغ ادعای بیمه و مبلغ پرداختی بیمار را وارد کنید.',
    'How do I create a billing record?',
    'Go to **Billing**, click **Add Record**. Select the patient and the procedure code (from the predefined list). Enter the amount, insurance claim amount, and patient pay amount. Set the billing date and any notes. Save the record.',
    'billing',
    ARRAY['billing', 'patients']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'بخش حسابداری چیست؟',
    'ماژول **حسابداری** دفترداری دوطرفه ارائه می‌دهد: نمودار حساب‌ها، سند حسابداری با ردیف‌های بدهکار/بستانکار، و گزارش‌های مالی (صورت سود و زیان، ترازنامه، مانده حساب‌ها).',
    'What are Procedure Codes?',
    'Procedure Codes are standardized codes for medical services your clinic provides (e.g., consultation, ultrasound, lab test). Each code has a description, category, default price, and insurance coverage rate. Admins can manage the procedure code list from **Billing > Procedure Codes**.',
    'billing',
    ARRAY['billing', 'lab']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه گزارش مالی تولید کنم؟',
    'به **حسابداری** > **گزارش‌ها** بروید. نوع گزارش را انتخاب کنید: صورت سود و زیان، ترازنامه، مانده حساب‌ها، یا گزارش دوره‌ای.

---',
    'How do I update a payment status?',
    'In the Billing records list, click on a record''s status field. You can change the status to:
- **Pending** — Not yet paid.
- **Paid** — Payment received.
- **Partial** — Partially paid.
- **Cancelled** — Billing cancelled.

Only admins can change payment status.',
    'billing',
    ARRAY['billing']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I view a patient''s balance?',
    'From the Billing page, use the **Patient Balance** search. Enter the patient''s name or ID to see their total billed amount, paid amount, and outstanding balance.',
    'How do I view a patient''s balance?',
    'From the Billing page, use the **Patient Balance** search. Enter the patient''s name or ID to see their total billed amount, paid amount, and outstanding balance.',
    'billing',
    ARRAY['billing', 'patients']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I generate a billing report?',
    'Go to **Billing** > **Reports**. You can filter by date range, patient, status, or procedure category. The report summarizes total billed, collected, pending, and other financial metrics.',
    'How do I generate a billing report?',
    'Go to **Billing** > **Reports**. You can filter by date range, patient, status, or procedure category. The report summarizes total billed, collected, pending, and other financial metrics.',
    'billing',
    ARRAY['billing', 'patients']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'What is the Accounting section?',
    'The **Accounting** module provides double-entry bookkeeping:
- **Chart of Accounts** — A hierarchical list of all financial accounts (assets, liabilities, equity, revenue, expenses).
- **Journal Entries** — Records of financial transactions with debit and credit lines.
- **Financial Reports** — Income statement, balance sheet, trial balance, and period reports.

This is an admin-only feature for comprehensive financial tracking.',
    'What is the Accounting section?',
    'The **Accounting** module provides double-entry bookkeeping:
- **Chart of Accounts** — A hierarchical list of all financial accounts (assets, liabilities, equity, revenue, expenses).
- **Journal Entries** — Records of financial transactions with debit and credit lines.
- **Financial Reports** — Income statement, balance sheet, trial balance, and period reports.

This is an admin-only feature for comprehensive financial tracking.',
    'billing',
    ARRAY['billing', 'scheduling']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I create a journal entry?',
    'Go to **Accounting** > **Journal Entries** > **Add Entry**. Set the entry date, description, and reference. Add one or more line items, each specifying an account, debit amount, and/or credit amount. The total debits must equal total credits. Save to post the entry.',
    'How do I create a journal entry?',
    'Go to **Accounting** > **Journal Entries** > **Add Entry**. Set the entry date, description, and reference. Add one or more line items, each specifying an account, debit amount, and/or credit amount. The total debits must equal total credits. Save to post the entry.',
    'billing',
    ARRAY['billing', 'patients']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I generate a financial report?',
    'Go to **Accounting** > **Reports**. Choose the report type:
- **Income Statement** — Revenue vs. expenses for a period.
- **Balance Sheet** — Assets, liabilities, and equity at a point in time.
- **Trial Balance** — All account balances to verify debits = credits.
- **Period Report** — Custom date range summary.

---',
    'How do I generate a financial report?',
    'Go to **Accounting** > **Reports**. Choose the report type:
- **Income Statement** — Revenue vs. expenses for a period.
- **Balance Sheet** — Assets, liabilities, and equity at a point in time.
- **Trial Balance** — All account balances to verify debits = credits.
- **Period Report** — Custom date range summary.

---',
    'billing',
    ARRAY['billing']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه انبار داروخانه را مدیریت کنم؟',
    'به بخش **انبار** بروید. خلاصه آماری (تعداد محصولات، ارزش موجودی، هشدار کمبود، موجودی صفر) نمایش داده می‌شود. می‌توانید محصولات اضافه کنید، جابجایی موجودی ثبت کنید و هشدارهای کمبود را ببینید.',
    'How do I manage pharmacy inventory?',
    'Go to **Inventory**. The page shows summary cards (total products, stock value, low stock alerts, out of stock). You can:
- **Add products** with SKU, barcode, category, purchase/selling price, and stock levels.
- **Record stock movements** (stock in, stock out, adjustment) with quantity and unit price.
- **View low stock alerts** when products fall below the minimum stock level.',
    'inventory',
    ARRAY['inventory', 'patients', 'prescriptions']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه هزینه ملزومات را پیگیری کنم؟',
    'به بخش **ملزومات** بروید. هزینه‌های ماهانه لوازم کلینیک (دستکش، سرنگ، ضدعفونی‌کننده و غیره) را مشاهده و مدیریت کنید.

---',
    'How do I record a stock movement?',
    'Go to **Inventory** > **Stock Movements** > **Add Movement**. Select the product, movement type (in/out/adjustment), quantity, unit price, and reference (optional). The system automatically updates the product''s current stock level.',
    'inventory',
    ARRAY['inventory']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I track consumable expenses?',
    'Go to **Consumables**. This section tracks monthly clinic supplies (e.g., gloves, syringes, disinfectants). You can:
- View expenses by month and year.
- Add or update expense amounts for each consumable item.
- Export monthly data.
- View yearly summary with stat cards.',
    'How do I track consumable expenses?',
    'Go to **Consumables**. This section tracks monthly clinic supplies (e.g., gloves, syringes, disinfectants). You can:
- View expenses by month and year.
- Add or update expense amounts for each consumable item.
- Export monthly data.
- View yearly summary with stat cards.',
    'inventory',
    ARRAY['inventory']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'What are Consumable Items?',
    'Consumable Items are predefined clinic supplies tracked on a monthly basis. Admins can add, edit, or deactivate items from the Consumables page. Each item tracks monthly expense amounts.

---',
    'What are Consumable Items?',
    'Consumable Items are predefined clinic supplies tracked on a monthly basis. Admins can add, edit, or deactivate items from the Consumables page. Each item tracks monthly expense amounts.

---',
    'inventory',
    ARRAY['inventory']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'بخش لیدها چیست؟',
    'بخش **لیدها** خط لوله CRM برای پیگیری بیماران بالقوه قبل از تبدیل شدن به بیمار واقعی است. لیدها از مراحل عبور می‌کنند: جدید > تماس گرفته شده > واجد شرایط > نوبت رزرو شده > ویزیت شده > تبدیل شده > از دست رفته.',
    'What is the Leads section?',
    'The **Leads** section is a CRM (Customer Relationship Management) pipeline for tracking potential patients before they become actual patients. Leads go through stages:
1. **New** — Initial inquiry received.
2. **Contacted** — First contact made.
3. **Qualified** — Lead is a good fit.
4. **Appointment Booked** — Appointment scheduled.
5. **Visited** — Patient came in.
6. **Converted** — Became a registered patient.
7. **Lost** — Lead did not convert.',
    'other',
    ARRAY['other', 'patients', 'scheduling']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه لید جدید ایجاد کنم؟',
    'به **لیدها** > **+ افزودن لید** بروید. اطلاعات پایه (نام، تلفن، کد ملی، منبع لید، کمپین)، انتساب (پارامترهای UTM)، و جزئیات (خدمت مورد انتظار، اولویت، مسئول پیگیری) را وارد کنید.',
    'How do I create a new lead?',
    'Go to **Leads** > **+ Add Lead**. Fill in:
- **Basic Info** — Name, phone, national ID, lead source, campaign name, notes.
- **Attribution** — UTM parameters (source, medium, campaign), landing page URL, referrer URL, marketing consent.
- **Details** — Expected service, expected visit type, estimated value, priority, assigned staff/doctor, next follow-up date, tags.',
    'other',
    ARRAY['other', 'patients']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه لید را به بیمار تبدیل کنم؟',
    'صفحه جزئیات لید را باز کنید. روی **تبدیل به بیمار** کلیک کنید. سیستم پرونده بیمار جدیدی ایجاد کرده و لید را به عنوان «تبدیل شده» علامت‌گذاری می‌کند.',
    'How do I convert a lead to a patient?',
    'Open the lead detail page. Click **Convert to Patient**. The system will:
1. Create a new patient record using the lead''s information.
2. Mark the lead as "converted."
3. Link the converted patient to the lead record.',
    'other',
    ARRAY['other', 'patients']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه لید را به عنوان از دست رفته علامت‌گذاری کنم؟',
    'در صفحه جزئیات لید، روی **علامت‌گذاری به عنوان از دست رفته** کلیک کنید. دلیل را انتخاب کنید: عدم علاقه، بودجه، رقیب، عدم دسترسی، شماره اشتباه، تکراری یا سایر.

---',
    'How do I mark a lead as lost?',
    'On the lead detail page, click **Mark as Lost**. You''ll be prompted to select a reason:
- Not interested
- Budget constraints
- Chose competitor
- Unreachable
- Wrong number
- Duplicate lead
- Other',
    'other',
    ARRAY['other']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I record a contact activity for a lead?',
    'On the lead detail page, click **Record Contact**. Add a note about the contact (phone call, meeting, message). The activity is logged in the lead''s timeline with a timestamp.',
    'How do I record a contact activity for a lead?',
    'On the lead detail page, click **Record Contact**. Add a note about the contact (phone call, meeting, message). The activity is logged in the lead''s timeline with a timestamp.',
    'other',
    ARRAY['other', 'messaging']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'What are Lead Sources?',
    'Lead Sources track where your potential patients come from. Examples include Instagram, Google Ads, Google Search, website, referral, walk-in, WhatsApp, Telegram, and phone calls. Go to **Lead Sources** to manage the list. Each source has a name, type, category, color, and active status.',
    'What are Lead Sources?',
    'Lead Sources track where your potential patients come from. Examples include Instagram, Google Ads, Google Search, website, referral, walk-in, WhatsApp, Telegram, and phone calls. Go to **Lead Sources** to manage the list. Each source has a name, type, category, color, and active status.',
    'other',
    ARRAY['other', 'patients', 'telegram']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I filter and search leads?',
    'The Leads page provides:
- **Search** by name, phone, or national ID.
- **Filter** by status, priority, source, assigned staff/doctor, and date range.
- **Summary cards** showing counts for each pipeline stage.
- **Sort** by creation date, last activity, or next follow-up.

---',
    'How do I filter and search leads?',
    'The Leads page provides:
- **Search** by name, phone, or national ID.
- **Filter** by status, priority, source, assigned staff/doctor, and date range.
- **Summary cards** showing counts for each pipeline stage.
- **Sort** by creation date, last activity, or next follow-up.

---',
    'other',
    ARRAY['other', 'patients']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه به همکار پیام بفرستم؟',
    'به بخش **پیام‌رسانی** بروید. **نگارش پیام** را بزنید. گیرنده را انتخاب کنید (جستجو بر اساس نام یا نقش)، موضوع و متن پیام را وارد کنید و ارسال کنید.',
    'How do I send a message to another staff member?',
    'Go to **Messaging**. Click **Compose**. Select the recipient (search by name or role), enter a subject and message body, and send. You can mark messages as confidential if needed.',
    'other',
    ARRAY['other', 'patients', 'messaging']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه پیام‌های خوانده‌نشده را ببینم؟',
    'نوار کناری تعداد پیام‌های خوانده‌نشده را در کنار آیتم پیام‌رسانی نشان می‌دهد. همچنین در صفحه پیام‌رسانی، پیام‌های خوانده‌نشده برجسته نمایش داده می‌شوند.

---',
    'How do I view my inbox and sent messages?',
    'The Messaging page has two tabs: **Inbox** (received messages) and **Sent** (messages you''ve sent). Unread messages are highlighted. Click on a message to view its full content.',
    'other',
    ARRAY['other', 'messaging']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I send a message to a patient?',
    'Doctors can send messages to patients from the Messaging page. Select the patient as the recipient. The patient will see the message in their **Patient Messaging** section.',
    'How do I send a message to a patient?',
    'Doctors can send messages to patients from the Messaging page. Select the patient as the recipient. The patient will see the message in their **Patient Messaging** section.',
    'other',
    ARRAY['other', 'patients', 'messaging']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I know if I have unread messages?',
    'The sidebar shows an unread message count badge next to the Messaging menu item. Additionally, the messaging page highlights unread messages in the inbox.',
    'How do I know if I have unread messages?',
    'The sidebar shows an unread message count badge next to the Messaging menu item. Additionally, the messaging page highlights unread messages in the inbox.',
    'other',
    ARRAY['other', 'messaging']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'Can I delete a message?',
    'Yes. You can delete messages you''ve sent or received. Deleted messages are hidden from your view only (the other party can still see them unless they also delete it).

---',
    'Can I delete a message?',
    'Yes. You can delete messages you''ve sent or received. Deleted messages are hidden from your view only (the other party can still see them unless they also delete it).

---',
    'other',
    ARRAY['other', 'messaging']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه ورود/خروج روزانه را ثبت کنم؟',
    'به بخش **حضور و غیاب** بروید. هنگام ورود، روی **ورود** کلیک کنید. هنگام خروج، روی **خروج** کلیک کنید. سیستم زمان ورود و خروج و ساعات کاری را محاسبه می‌کند.',
    'How do I manage staff members?',
    'Go to **Staff** (admin only). The page shows:
- Staff list with stat cards (total, active, inactive, today''s present count).
- Search and filter by status.
- Click **Add Staff** to create a new staff profile linked to a user account.',
    'staff',
    ARRAY['staff', 'login', 'patients', 'attendance', 'profile']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'تفاوت برنامه و حضور و غیاب چیست؟',
    '- **برنامه** ساعت‌های کاری مورد انتظار برای هر روز هفته را تعریف می‌کند (برنامه‌ریزی).
- **حضور و غیاب** زمان‌های ورود/خروج واقعی برای تاریخ‌های مشخص را ثبت می‌کند (پیگیری).

---',
    'How do I check in / check out for the day?',
    'Go to **Attendance** (clinic staff role). Click **Check In** when you arrive. The system records your check-in time. When leaving, click **Check Out**. The system records your check-out time and calculates your worked hours.',
    'staff',
    ARRAY['staff', 'login', 'patients', 'scheduling', 'attendance']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I view my attendance history?',
    'Go to **Attendance** > **My Attendance**. You''ll see a table of your attendance records with dates, status (present, late, absent, leave), check-in/out times, and worked hours.',
    'How do I view my attendance history?',
    'Go to **Attendance** > **My Attendance**. You''ll see a table of your attendance records with dates, status (present, late, absent, leave), check-in/out times, and worked hours.',
    'staff',
    ARRAY['staff', 'attendance']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How does the admin view staff attendance?',
    'Admins go to **Attendance** > **Report**. The report shows all staff attendance for a selected period, with filtering by date, status, and staff member. Admins can also bulk-update attendance entries.',
    'How does the admin view staff attendance?',
    'Admins go to **Attendance** > **Report**. The report shows all staff attendance for a selected period, with filtering by date, status, and staff member. Admins can also bulk-update attendance entries.',
    'staff',
    ARRAY['staff', 'attendance']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I set a staff member''s weekly schedule?',
    'Admins go to **Staff**, select a staff member, and set their weekly schedule (working hours for each day of the week). The schedule determines expected attendance and is visible on the staff detail page.',
    'How do I set a staff member''s weekly schedule?',
    'Admins go to **Staff**, select a staff member, and set their weekly schedule (working hours for each day of the week). The schedule determines expected attendance and is visible on the staff detail page.',
    'staff',
    ARRAY['staff', 'scheduling', 'attendance']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'What is the difference between Attendance and Schedule?',
    '- **Schedule** defines expected working hours for each day of the week (planning).
- **Attendance** records actual check-in/check-out times for specific dates (tracking).
The system compares scheduled hours against actual attendance to determine late arrivals or absences.

---',
    'What is the difference between Attendance and Schedule?',
    '- **Schedule** defines expected working hours for each day of the week (planning).
- **Attendance** records actual check-in/check-out times for specific dates (tracking).
The system compares scheduled hours against actual attendance to determine late arrivals or absences.

---',
    'staff',
    ARRAY['staff', 'scheduling', 'attendance']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه حساب‌های کاربری را مدیریت کنم؟',
    'به بخش **کاربران** (فقط مدیر) بروید. کاربران با تب‌های همه/در انتظار/تأیید شده/رد شده نمایش داده می‌شوند. می‌توانید ثبت‌نام‌ها را تأیید، رد، فعال یا غیرفعال کنید.',
    'How do I manage user accounts?',
    'Go to **Users** (admin only). The page shows all registered users with tabs:
- **All** — All users.
- **Pending** — Awaiting approval.
- **Approved** — Active users.
- **Rejected** — Denied registrations.

You can approve, reject, activate, or deactivate user accounts.',
    'settings',
    ARRAY['settings', 'patients']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه تنظیمات پیامک را پیکربندی کنم؟',
    'به **تنظیمات مدیر** > **مدیریت اعتبار پیامک** بروید. اعتبار باقی‌مانده، تعداد ارسال شده و اعتبار کل را ببینید. می‌توانید اعتبار جدید تنظیم کنید و پیامک را فعال/غیرفعال کنید.',
    'How do I approve a new doctor''s registration?',
    'Go to **Users** > **Pending** tab. Find the doctor''s registration. Click **Approve** to grant access or **Reject** to deny it. Approved doctors can log in and access their role-specific features.',
    'settings',
    ARRAY['settings', 'messaging']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه تنظیمات اعلان را پیکربندی کنم؟',
    'به **تنظیمات مدیر** > **تنظیمات اعلان** بروید. اعلان‌ها بر اساس دسته‌بندی (احراز هویت، بیمار، نوبت، پیام‌رسانی) سازمان‌دهی شده‌اند. برای هر رویداد می‌توانید کانال‌های پیامک و تلگرام را به طور مستقل فعال/غیرفعال کنید.',
    'How do I configure SMS settings?',
    'Go to **Admin Settings** > **SMS Credit Management**. You can:
- View remaining SMS credits, total sent, and total allocated.
- Set a new credit limit.
- Use quick-increase buttons to add credits.
- Enable or disable SMS globally.',
    'settings',
    ARRAY['settings', 'patients', 'scheduling', 'messaging', 'telegram']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'گزارش‌های حسابرسی چیست؟',
    'به **مدیریت > گزارش‌های حسابرسی** بروید. گزارش حسابرسی هر عملیات مهم در سیستم را ثبت می‌کند: چه کسی، چه چیزی، چه زمانی، و چه تغییری ایجاد شده است.

---',
    'How do I configure notification settings?',
    'Go to **Admin Settings** > **Notification Settings**. Notifications are organized by category:
- **Auth** — Registration and OTP notifications.
- **Patient** — Patient creation notifications.
- **Appointment** — Booking, confirmation, and rejection notifications.
- **Messaging** — Message notifications between staff and patients.

For each event, you can enable/disable **SMS** and **Telegram** channels independently.',
    'settings',
    ARRAY['settings', 'patients', 'scheduling', 'messaging', 'telegram']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'What are Audit Logs?',
    'Go to **Admin > Audit Logs**. The audit log records every significant action in the system:
- Who performed the action.
- What entity was affected (patient, appointment, etc.).
- When it happened (timestamp).
- What changed (old values vs. new values).
- IP address and browser information.

This is essential for compliance and security tracking. Only admins can access audit logs.',
    'What are Audit Logs?',
    'Go to **Admin > Audit Logs**. The audit log records every significant action in the system:
- Who performed the action.
- What entity was affected (patient, appointment, etc.).
- When it happened (timestamp).
- What changed (old values vs. new values).
- IP address and browser information.

This is essential for compliance and security tracking. Only admins can access audit logs.',
    'settings',
    ARRAY['settings', 'patients', 'scheduling']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I view what changed in an audit log entry?',
    'In the Audit Logs table, click on any row to open a detail dialog. It shows a side-by-side comparison of old values and new values for each changed field. You can also see the user agent and IP address of the person who made the change.',
    'How do I view what changed in an audit log entry?',
    'In the Audit Logs table, click on any row to open a detail dialog. It shows a side-by-side comparison of old values and new values for each changed field. You can also see the user agent and IP address of the person who made the change.',
    'settings',
    ARRAY['settings']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'What is the Clinic Settings page?',
    'Go to **Admin Settings**. This is a key-value configuration store for clinic-wide settings. Admins can modify settings that affect how the entire system behaves (clinic name, working hours, SMS provider configuration, etc.).

---',
    'What is the Clinic Settings page?',
    'Go to **Admin Settings**. This is a key-value configuration store for clinic-wide settings. Admins can modify settings that affect how the entire system behaves (clinic name, working hours, SMS provider configuration, etc.).

---',
    'settings',
    ARRAY['settings']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه گزارش روزانه ایجاد کنم؟',
    'به **گزارش‌های روزانه** > تب **ذخیره گزارش** بروید. تاریخ، بیمار، انواع ویزیت، اقدامات انجام شده، حق‌الزحمه دریافتی، روش پرداخت و یادداشت‌ها را وارد کنید.',
    'How do I create a daily report?',
    'Go to **Daily Reports** > **Save Report** tab. Select the date, patient, visit types seen, procedures performed, fee collected, payment method, and any notes. Save the report.',
    'accounting',
    ARRAY['accounting', 'patients', 'billing']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چه آماری برای گزارش‌های روزانه موجود است؟',
    'به **گزارش‌های روزانه** > **آمار** بروید. آمار تجمیعی شامل تعداد کل گزارش‌ها، حق‌الزحمه کل، میانگین حق‌الزحمه و روندها نمایش داده می‌شود.

---',
    'How do I view past daily reports?',
    'Go to **Daily Reports** > **View Reports** tab. Reports are listed chronologically and can be filtered by date range, doctor, or visit type.',
    'accounting',
    ARRAY['accounting']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'What statistics are available for daily reports?',
    'Go to **Daily Reports** > **Stats**. The system provides aggregated statistics including total reports, total fees collected, average fee per visit, most common visit types, and trends over time.',
    'What statistics are available for daily reports?',
    'Go to **Daily Reports** > **Stats**. The system provides aggregated statistics including total reports, total fees collected, average fee per visit, most common visit types, and trends over time.',
    'accounting',
    ARRAY['accounting', 'lab']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I manage visit types for daily reports?',
    'Go to **Daily Reports** > **Visit Types**. These are separate from clinical visit types and are specifically used for daily report categorization. You can add, edit, or deactivate report visit types.

---',
    'How do I manage visit types for daily reports?',
    'Go to **Daily Reports** > **Visit Types**. These are separate from clinical visit types and are specifically used for daily report categorization. You can add, edit, or deactivate report visit types.

---',
    'accounting',
    ARRAY['accounting', 'clinical']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I update my profile information?',
    'Go to **My Profile**. You can update:
- Full name
- Organization name
- Phone number
- Notification preferences',
    'How do I update my profile information?',
    'Go to **My Profile**. You can update:
- Full name
- Organization name
- Phone number
- Notification preferences',
    'settings',
    ARRAY['settings', 'profile']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I change my password?',
    'Go to **My Profile** > **Change Password**. Enter your current password and the new password twice. Click **Save** to update.',
    'How do I change my password?',
    'Go to **My Profile** > **Change Password**. Enter your current password and the new password twice. Click **Save** to update.',
    'settings',
    ARRAY['settings', 'login', 'profile']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I switch between light and dark mode?',
    'Click the **theme toggle** icon in the top navigation bar. The system supports full dark mode across all pages. Your preference is saved locally.',
    'How do I switch between light and dark mode?',
    'Click the **theme toggle** icon in the top navigation bar. The system supports full dark mode across all pages. Your preference is saved locally.',
    'settings',
    ARRAY['settings']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I switch between Farsi and English?',
    'Click the **language toggle** button in the top navigation bar. The system switches between Farsi (Persian, RTL) and English (LTR). Your preference is remembered across sessions.

---',
    'How do I switch between Farsi and English?',
    'Click the **language toggle** button in the top navigation bar. The system switches between Farsi (Persian, RTL) and English (LTR). Your preference is remembered across sessions.

---',
    'settings',
    ARRAY['settings']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه سؤال پشتیبانی بپرسم؟',
    'از قابلیت **پشتیبانی** استفاده کنید. سؤال خود را تایپ کنید و دستیار هوش مصنوعی پاسخ خواهد داد. اگر پاسخ مفید بود، تأیید کنید. اگر نه، سؤال به مدیر ارجاع داده می‌شود.',
    'How do I ask a support question?',
    'Use the **Support** feature to ask questions about using the system. Type your question and the AI assistant will provide an answer. If the answer is helpful, you can confirm it. If not, the question can be escalated to an admin.',
    'general',
    ARRAY['general']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'مدیر چگونه FAQ را مدیریت کند؟',
    'به **مدیریت > مدیریت FAQ** بروید. مدیران می‌توانند تمام مقالات FAQ منتشرشده را مشاهده کنند، مقالات در انتظار تأیید را بررسی و تأیید/رد کنند، و مقالات جدید به صورت دستی ایجاد کنند.

---',
    'What happens after I confirm an AI answer?',
    'When you confirm an AI-generated answer, it may be promoted to the FAQ knowledge base for other users to benefit from. Admins review and approve entries before they are published.',
    'general',
    ARRAY['general']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do admins manage the FAQ?',
    'Go to **Admin > FAQ Management**. Admins can:
- View all published FAQ entries.
- Review pending entries (from AI-generated or user-confirmed answers).
- Approve or reject pending entries.
- Create, edit, or delete FAQ entries manually.
- Filter by category (general, billing, scheduling, clinical, patients, prescriptions, lab results, inventory, accounting, staff, settings, other).',
    'How do admins manage the FAQ?',
    'Go to **Admin > FAQ Management**. Admins can:
- View all published FAQ entries.
- Review pending entries (from AI-generated or user-confirmed answers).
- Approve or reject pending entries.
- Create, edit, or delete FAQ entries manually.
- Filter by category (general, billing, scheduling, clinical, patients, prescriptions, lab results, inventory, accounting, staff, settings, other).',
    'general',
    ARRAY['general', 'patients', 'prescriptions', 'lab', 'billing', 'inventory', 'settings', 'clinical']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'What does the support ticket lifecycle look like?',
    '1. User asks a question via the support interface.
2. AI generates an answer (using Gemini or Groq).
3. User can confirm (if helpful) or escalate (if not satisfactory).
4. Confirmed answers may become FAQ entries pending admin approval.
5. Escalated tickets are reviewed by admins who can resolve them manually.
6. Admins can link resolved answers back to the FAQ system.

---',
    'What does the support ticket lifecycle look like?',
    '1. User asks a question via the support interface.
2. AI generates an answer (using Gemini or Groq).
3. User can confirm (if helpful) or escalate (if not satisfactory).
4. Confirmed answers may become FAQ entries pending admin approval.
5. Escalated tickets are reviewed by admins who can resolve them manually.
6. Admins can link resolved answers back to the FAQ system.

---',
    'general',
    ARRAY['general']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'What is the Telegram Mini App?',
    'The Telegram Mini App (`/tg`) is a separate interface within Telegram that allows patients to interact with the clinic. It provides:
- Login via Telegram or phone number.
- Browse services and doctors.
- Book appointments.
- View upcoming and past appointments.
- Manage their profile.',
    'What is the Telegram Mini App?',
    'The Telegram Mini App (`/tg`) is a separate interface within Telegram that allows patients to interact with the clinic. It provides:
- Login via Telegram or phone number.
- Browse services and doctors.
- Book appointments.
- View upcoming and past appointments.
- Manage their profile.',
    'general',
    ARRAY['general', 'login', 'patients', 'scheduling', 'telegram', 'profile']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I link my Telegram account to my CRM account?',
    'Go to **My Profile** and click **Link Telegram**. You''ll receive a linking code. Open Telegram, start the clinic''s bot, and send the code. Your Telegram account will be linked, enabling Telegram-based notifications and the mini app.',
    'How do I link my Telegram account to my CRM account?',
    'Go to **My Profile** and click **Link Telegram**. You''ll receive a linking code. Open Telegram, start the clinic''s bot, and send the code. Your Telegram account will be linked, enabling Telegram-based notifications and the mini app.',
    'general',
    ARRAY['general', 'messaging', 'telegram', 'profile']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I unlink my Telegram account?',
    'Go to **My Profile** > **Telegram Status** > **Unlink**. This disconnects your Telegram account from the CRM. You will no longer receive Telegram notifications.

---',
    'How do I unlink my Telegram account?',
    'Go to **My Profile** > **Telegram Status** > **Unlink**. This disconnects your Telegram account from the CRM. You will no longer receive Telegram notifications.

---',
    'general',
    ARRAY['general', 'telegram', 'profile']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه حساب کاربری ایجاد کنم؟',
    'به دو روش:
1. **ثبت‌نام آنلاین** — به صفحه ثبت‌نام بروید، شماره تلفن و رمز عبور را وارد کنید. حساب شما تا تأیید کلینیک در وضعیت «در انتظار» خواهد بود.
2. **ثبت‌نام در کلینیک** — کارکنان کلینیک هنگام اولین مراجعه حساب شما را ایجاد می‌کنند.',
    'How do I create an account?',
    'You can create an account in two ways:
1. **Self-registration** — Go to the Register page, enter your phone number and password. Your account will be in "pending" status until the clinic approves it.
2. **Clinic registration** — The clinic staff creates your account when you first visit. You''ll receive your login credentials.',
    'general',
    ARRAY['general', 'login', 'patients']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'رمز عبورم را فراموش کرده‌ام. چه کار کنم؟',
    'به صفحه ورود بروید و «فراموشی رمز عبور» را کلیک کنید. شماره تلفن ثبت‌شده را وارد کنید. یک رمز یکبار مصرف از طریق پیامک دریافت خواهید کرد. OTP و رمز جدید را وارد کنید.',
    'I forgot my password. What should I do?',
    'Go to the Login page and click "Forgot Password." Enter your registered phone number. You''ll receive a one-time password (OTP) via SMS. Enter the OTP and set a new password.',
    'general',
    ARRAY['general', 'login', 'patients', 'messaging', 'attendance']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'آیا می‌توانم با موبایل از سیستم استفاده کنم؟',
    'بله. سیستم کاملاً واکنش‌گرا است و در مرورگرهای موبایل کار می‌کند. همچنین اگر از تلگرام استفاده می‌کنید، **اپلیکیشن تلگرام** تجربه بومی موبایلی با امکانات رزرو نوبت، مشاهده نوبت‌ها و مدیریت پروفایل فراهم می‌کند.

---',
    'Can I use the system on my phone?',
    'Yes. The system is fully responsive and works on mobile browsers. Additionally, if you use Telegram, you can use the **Telegram Mini App** for a native mobile experience with booking, appointment viewing, and profile management.

---',
    'general',
    ARRAY['general', 'scheduling', 'telegram', 'profile']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه نوبت رزرو کنم؟',
    'سه گزینه دارید:
1. **صفحه رزرو عمومی** — به `/booking` بروید، خدمت را انتخاب کنید، پزشک را انتخاب کنید، تاریخ و ساعت را انتخاب کنید، اطلاعات خود را وارد کنید و تأیید کنید.
2. **اپلیکیشن تلگرام** — ربات تلگرام را باز کنید، «رزرو نوبت» را بزنید و جادوی ۵ مرحله‌ای را دنبال کنید.
3. **از طریق کلینیک** — با تلفن یا حضوری با کلینیک تماس بگیرید.',
    'How do I book an appointment?',
    'You have three options:
1. **Public Booking Page** — Go to `/booking`, select a service, choose a doctor, pick a date and time, enter your information, and confirm.
2. **Telegram Mini App** — Open the Telegram bot, tap "Book Appointment," and follow the 5-step wizard.
3. **Through the clinic** — Call or visit the clinic and have staff book for you.',
    'scheduling',
    ARRAY['scheduling', 'attendance', 'telegram']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'برای رزرو نوبت نیاز به ورود دارم؟',
    'خیر. صفحه رزرو عمومی (`/booking`) نیازی به ورود ندارد. می‌توانید پزشکان، خدمات و زمان‌های در دسترس را مشاهده کنید و با وارد کردن نام، تلفن و کد ملی مستقیماً رزرو کنید.',
    'Do I need to log in to book an appointment?',
    'No. The public booking page (`/booking`) does not require login. You can browse available doctors, services, and time slots, and book directly by entering your name, phone number, and national ID.',
    'scheduling',
    ARRAY['scheduling', 'login', 'lab', 'attendance']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'پس از رزرو نوبت چه اتفاقی می‌افتد؟',
    'پس از رزرو، نوبت شما با وضعیت «در انتظار» ایجاد می‌شود. کارکنان کلینیک آن را بررسی و تأیید یا رد می‌کنند. پس از تأیید، پیامک تأیید دریافت خواهید کرد.',
    'What happens after I book an appointment?',
    'After booking, your appointment is created with a "pending" status. The clinic staff will review and confirm or reject it. You may receive an SMS confirmation once it''s approved.',
    'scheduling',
    ARRAY['scheduling', 'patients', 'messaging']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه نوبتم را لغو کنم؟',
    'برای لغو نوبت، مستقیماً با کلینیک از طریق تلفن یا سیستم پیام‌رسانی تماس بگیرید.',
    'How do I cancel an appointment?',
    'To cancel an appointment, contact the clinic directly by phone or through the messaging system. Cancellation through the self-service portal is not currently available; staff will handle cancellations on your behalf.',
    'scheduling',
    ARRAY['scheduling', 'lab', 'messaging']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'آیا می‌توانم زمان‌های در دسترس را قبل از رزرو ببینم؟',
    'بله. هنگام انتخاب پزشک و تاریخ، تمام زمان‌های در دسترس بر اساس برنامه پزشک نمایش داده می‌شوند.

---',
    'Can I see available time slots before booking?',
    'Yes. When you select a doctor and date during the booking process, the system shows all available time slots for that day based on the doctor''s schedule. Unavailable slots are hidden.',
    'scheduling',
    ARRAY['scheduling', 'lab']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'What doctors can I book with?',
    'The booking page shows all doctors who have set up their availability. Each doctor''s profile shows their specialty, experience, and the services they offer.

---',
    'What doctors can I book with?',
    'The booking page shows all doctors who have set up their availability. Each doctor''s profile shows their specialty, experience, and the services they offer.

---',
    'scheduling',
    ARRAY['scheduling', 'lab', 'profile']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه نوبت‌های آینده‌ام را ببینم؟',
    'وارد شوید و به **داشبورد** بروید. نوبت‌های آینده با تاریخ، ساعت، پزشک و وضعیت نمایش داده می‌شوند. در اپلیکیشن تلگرام، به **نوبت‌ها** > تب **آینده** بروید.',
    'How do I see my upcoming appointments?',
    'Log in and go to the **Dashboard**. Your upcoming appointments are displayed with date, time, doctor, and status. In the Telegram Mini App, go to **Appointments** > **Upcoming** tab.',
    'patients',
    ARRAY['patients', 'scheduling', 'telegram']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه نوبت‌های گذشته را ببینم؟',
    'در اپلیکیشن تلگرام به **نوبت‌ها** > تب **گذشته** بروید. در وب اپلیکیشن، داشبورد تاریخچه نوبت‌های اخیر را نشان می‌دهد.',
    'How do I view my past appointments?',
    'In the Telegram Mini App, go to **Appointments** > **Past** tab. In the web app, the dashboard shows recent appointment history.',
    'patients',
    ARRAY['patients', 'scheduling', 'telegram']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'آیا می‌توانم نسخه‌هایم را ببینم؟',
    'بیماران می‌توانند نسخه‌های خود را از طریق داشبورد مشاهده کنند. نسخه‌ها شامل نام دارو، دوز، دفعات مصرف و پزشک تجویزکننده هستند.

---',
    'Can I view my prescriptions?',
    'Patient users can view their prescriptions through the dashboard. Prescriptions show medication name, dosage, frequency, and prescribing doctor. For detailed prescription management, your doctor handles this on your behalf.',
    'patients',
    ARRAY['patients', 'prescriptions']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'Can I view my lab results?',
    'Lab results are managed by your doctor and lab staff. If results are available, your doctor will share them with you during a visit or through messaging. The patient dashboard may show recent results if shared.

---',
    'Can I view my lab results?',
    'Lab results are managed by your doctor and lab staff. If results are available, your doctor will share them with you during a visit or through messaging. The patient dashboard may show recent results if shared.

---',
    'patients',
    ARRAY['patients', 'lab']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه به پزشکم پیام بفرستم؟',
    'به **پیام‌رسانی بیمار** بروید. پزشک مورد نظر را انتخاب کنید، موضوع و پیام خود را وارد کنید و ارسال کنید.',
    'How do I send a message to my doctor?',
    'Go to **Patient Messaging**. Select the doctor you want to message, enter a subject and your message, and send. Your doctor will receive it in their messaging inbox.',
    'other',
    ARRAY['other', 'patients', 'messaging']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه بفهمم پزشکم پاسخ داده؟',
    'شاخص پیام خوانده‌نشده در داشبورد و بخش پیام‌رسانی بیمار نمایش داده می‌شود. پیام را باز کنید تا پاسخ را بخوانید.

---',
    'How do I know if my doctor replied?',
    'You''ll see an unread message indicator on your dashboard and in the Patient Messaging section. Open the message to read the reply.',
    'other',
    ARRAY['other', 'patients', 'messaging']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'Are my messages private?',
    'Messages are confidential communications between you and the clinic staff. Messages marked as "confidential" have additional access restrictions. Only you and the intended recipient(s) can read them.

---',
    'Are my messages private?',
    'Messages are confidential communications between you and the clinic staff. Messages marked as "confidential" have additional access restrictions. Only you and the intended recipient(s) can read them.

---',
    'other',
    ARRAY['other', 'messaging']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I access the Telegram Mini App?',
    'Open Telegram, search for the clinic''s bot, and start a conversation. The bot will guide you through login (via Telegram account or phone number). Once authenticated, you can access the mini app features.',
    'How do I access the Telegram Mini App?',
    'Open Telegram, search for the clinic''s bot, and start a conversation. The bot will guide you through login (via Telegram account or phone number). Once authenticated, you can access the mini app features.',
    'general',
    ARRAY['general', 'login', 'patients', 'telegram']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'What can I do in the Telegram Mini App?',
    'The Telegram Mini App provides:
- **Book Appointments** — A 5-step wizard to select service, doctor, date, time, and confirm.
- **View Appointments** — Browse upcoming and past appointments with status badges.
- **Manage Profile** — Update your personal information (national ID, name, phone, birth date, address).
- **Quick Actions** — Home screen with next appointment and booking CTA.',
    'What can I do in the Telegram Mini App?',
    'The Telegram Mini App provides:
- **Book Appointments** — A 5-step wizard to select service, doctor, date, time, and confirm.
- **View Appointments** — Browse upcoming and past appointments with status badges.
- **Manage Profile** — Update your personal information (national ID, name, phone, birth date, address).
- **Quick Actions** — Home screen with next appointment and booking CTA.',
    'general',
    ARRAY['general', 'scheduling', 'telegram', 'profile']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'How do I link my Telegram account to my clinic account?',
    'In the Telegram Mini App, go to **Profile**. If your account isn''t linked, you''ll see a linking option. Alternatively, in the web app, go to **My Profile** > **Link Telegram** and follow the instructions.',
    'How do I link my Telegram account to my clinic account?',
    'In the Telegram Mini App, go to **Profile**. If your account isn''t linked, you''ll see a linking option. Alternatively, in the web app, go to **My Profile** > **Link Telegram** and follow the instructions.',
    'general',
    ARRAY['general', 'telegram', 'profile']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'The mini app asks me to complete my profile. Why?',
    'If your Telegram account isn''t yet associated with a patient record in the clinic''s system, the mini app will prompt you to enter your information (name, national ID, phone, etc.). This creates or links your patient record so the clinic can serve you properly.

---',
    'The mini app asks me to complete my profile. Why?',
    'If your Telegram account isn''t yet associated with a patient record in the clinic''s system, the mini app will prompt you to enter your information (name, national ID, phone, etc.). This creates or links your patient record so the clinic can serve you properly.

---',
    'general',
    ARRAY['general', 'patients', 'telegram', 'profile']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه اطلاعات شخصی‌ام را به‌روزرسانی کنم؟',
    '- **وب اپلیکیشن** — به **پروفایل من** بروید و اطلاعات را ویرایش کنید.
- **اپلیکیشن تلگرام** — به **پروفایل** بروید، اطلاعات را ویرایش و **ذخیره** را بزنید.',
    'How do I update my personal information?',
    '- **Web app** — Go to **My Profile** and update your name, phone, or other details.
- **Telegram Mini App** — Go to **Profile**, edit your information, and tap **Save**.',
    'settings',
    ARRAY['settings', 'telegram', 'profile']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چه اطلاعاتی از من در کلینیک ذخیره می‌شود؟',
    'کلینیک اطلاعات زیر را ذخیره می‌کند:
- **اطلاعات هویتی** — نام، کد ملی، تلفن، تاریخ تولد، آدرس، وضعیت تأهل.
- **سابقه پزشکی** — بیماری‌ها، داروها، آلرژی‌ها، سابقه خانوادگی.
- **بیمه** — نوع و کد بیمه.
- **پرونده بالینی** — ویزیت‌ها، نسخه‌ها، نتایج آزمایش، علائم حیاتی.
- **سلامت باروری** (در صورت لزوم) — تاریخچه قاعدگی، بارداری‌ها، تاریخچه جراحی.
- **پیوست‌ها** — فایل‌های آپلود شده (سونوگرافی، گزارش آزمایش و غیره).
- **رضایت‌نامه‌ها** — رضایت شما برای پردازش اطلاعات.',
    'What information does the clinic store about me?',
    'The clinic stores:
- **Demographics** — Name, national ID, phone, birth date, address, marital status.
- **Medical history** — Diseases, medications, allergies, family history.
- **Insurance** — Insurance type and code.
- **Clinical records** — Visits, prescriptions, lab results, vital signs.
- **Reproductive health** (if applicable) — Menstrual history, pregnancies, surgical history.
- **Attachments** — Uploaded files (ultrasounds, lab reports, etc.).
- **Consent records** — Your consent for data processing.',
    'settings',
    ARRAY['settings', 'patients', 'prescriptions', 'lab', 'clinical']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'آیا اطلاعات پزشکی من امن است؟',
    'بله. سیستم اقدامات امنیتی متعددی اجرا می‌کند: رمزهای عبور رمزگذاری شده (bcrypt)، هدرهای امنیتی، گزارش‌های حسابرسی، کنترل دسترسی مبتنی بر نقش، و رضایت‌نامه‌های پردازش داده.',
    'Is my medical data secure?',
    'Yes. The system implements several security measures:
- Passwords are encrypted (bcrypt).
- All API communication is protected with security headers.
- Audit logs track all access to your records.
- Consent records document your data processing permissions.
- Confidential notes and messages have restricted access.
- The system uses role-based access control so staff only see information relevant to their role.',
    'settings',
    ARRAY['settings', 'login', 'messaging']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه درخواست حذف اطلاعاتم را بدهم؟',
    'مستقیماً با کلینیک تماس بگیرید. پرونده‌های بیماران به صورت حذف نرم حذف می‌شوند (نه دائمی) که یکپارچگی مسیر حسابرسی را حفظ می‌کند.',
    'How do I request deletion of my data?',
    'Contact the clinic directly to request data deletion or review. Patient records are soft-deleted (marked as deleted) rather than permanently removed, which preserves audit trail integrity. The clinic''s data handling practices should comply with applicable privacy regulations.

---',
    'settings',
    ARRAY['settings', 'patients']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چگونه به اپلیکیشن تلگرام دسترسی پیدا کنم؟',
    'تلگرام را باز کنید، ربات کلینیک را جستجو کنید و مکالمه را شروع کنید. ربات شما را از طریق ورود (حساب تلگرام یا شماره تلفن) راهنمایی می‌کند.',
    NULL,
    NULL,
    'general',
    ARRAY['general', 'login', 'patients', 'attendance', 'telegram']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'چه کارهایی در اپلیکیشن تلگرام می‌توانم انجام دهم؟',
    '- **رزرو نوبت** — جادوی ۵ مرحله‌ای برای انتخاب خدمت، پزشک، تاریخ، ساعت و تأیید.
- **مشاهده نوبت‌ها** — مرور نوبت‌های آینده و گذشته با نشانگرهای وضعیت.
- **مدیریت پروفایل** — به‌روزرسانی اطلاعات شخصی (کد ملی، نام، تلفن، تاریخ تولد، آدرس).',
    NULL,
    NULL,
    'general',
    ARRAY['general', 'scheduling', 'telegram', 'profile']::text[],
    'manual',
    true,
    1.0
  ),
  (
    'اپلیکیشن از من می‌خواهد پروفایلم را تکمیل کنم. چرا؟',
    'اگر حساب تلگرام شما هنوز با پرونده بیمار در سیستم کلینیک مرتبط نیست، اپلیکیشن از شما می‌خواهد اطلاعات خود (نام، کد ملی، تلفن و غیره) را وارد کنید. این کار پرونده بیمار شما را ایجاد یا پیوند می‌دهد.

---',
    NULL,
    NULL,
    'general',
    ARRAY['general', 'patients', 'telegram', 'profile']::text[],
    'manual',
    true,
    1.0
  );
